accounts:
  - name: alice
    coins: ["200000000rio"]
  - name: bob
    coins: ["100000000rio"]
validator:
  name: alice
  staked: "100000000rio"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["1000rio"]
genesis:
  chain_id: "realionetwork-test1"
  app_state:
    staking:
      params:
        bond_denom: "rio"
        historical_entries: "10"
        max_validators: "10"
        unbonding_time: "300000000000ns"
    mint:
      params:
        mint_denom: "rio"
    crisis:
      constant_fee:
        denom: "rio"


