name: Makefile CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and Install
      run: make install

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REALIO_NETWORK_CI }}
      - name: Publish new version
        run: |
          git config --global user.email "info@realio.fund"
          git config --global user.name "Release Bot"
          git tag -fa v0.0.1 -m "v0.0.1 tag"
          git push origin v0.0.1 --force
